export const Data = [
  {
    product: "Samsung Smart TV",
    price: 500,
    desc: "High-definition LED TV with Smart features.",
    availability: true,
  },
  {
    product: "LG 4K Ultra HD TV",
    price: 550,
    desc: "4K Ultra HD TV with HDR support and Dolby Atmos sound.",
    availability: false,
  },
  {
    product: "Sony Curved OLED TV",
    price: 600,
    desc: "Curved OLED TV with Quantum Dot technology.",
    availability: true,
  },
  {
    product: "Panasonic Android TV",
    price: 700,
    desc: "Android TV with voice control and built-in Chromecast.",
    availability: true,
  },
  {
    product: "TCL Budget LED TV",
    price: 450,
    desc: "Budget-friendly LED TV with HDMI and USB ports.",
    availability: false,
  },
  {
    product: "Vizio QLED TV",
    price: 650,
    desc: "QLED TV with Quantum Processor and Ambient Mode+.",
    availability: true,
  },
  {
    product: "Hisense Smart TV",
    price: 750,
    desc: "Smart TV with Apple TV app and AirPlay support.",
    availability: true,
  },
  {
    product: "Sharp Premium OLED TV",
    price: 800,
    desc: "Premium OLED TV with AI ThinQ and Dolby Vision IQ.",
    availability: true,
  },
  {
    product: "Insignia Full HD LED TV",
    price: 550,
    desc: "Full HD LED TV with USB multimedia playback.",
    availability: false,
  },
  {
    product: "Philips 8K Ultra HD TV",
    price: 850,
    desc: "8K Ultra HD TV with Quantum HDR and Direct Full Array.",
    availability: true,
  },
  {
    product: "RCA Android Smart TV",
    price: 600,
    desc: "Android Smart TV with Google Assistant and Netflix button.",
    availability: true,
  },
  {
    product: "Haier Quantum Dot QLED TV",
    price: 900,
    desc: "Quantum Dot QLED TV with Adaptive Sound+ technology.",
    availability: true,
  },
  {
    product: "Sceptre HDR LED TV",
    price: 700,
    desc: "HDR10+ compatible LED TV with Game Enhancer mode.",
    availability: false,
  },
  {
    product: "Westinghouse Ultra Slim 4K TV",
    price: 950,
    desc: "Ultra Slim 4K TV with Dolby Vision and DTS Virtual:X.",
    availability: true,
  },
  {
    product: "Element Basic LED TV",
    price: 500,
    desc: "Basic LED TV with VGA input for computer connection.",
    availability: true,
  },
  {
    product: "Haier 8K QLED TV",
    price: 1000,
    desc: "8K QLED TV with Quantum Processor 8K and Object Tracking Sound+.",
    availability: true,
  },
  {
    product: "Sharp Smart LED TV",
    price: 550,
    desc: "Smart LED TV with Netflix, Amazon Prime, and YouTube apps.",
    availability: false,
  },
  {
    product: "Toshiba Premium OLED TV",
    price: 1050,
    desc: "Premium OLED TV with 4K HDR gaming support and G-SYNC compatibility.",
    availability: true,
  },
  {
    product: "Hitachi Full HD Smart TV",
    price: 600,
    desc: "Full HD Smart TV with webOS and Magic Remote.",
    availability: true,
  },
  {
    product: "Sanyo Quantum Dot 4K QLED TV",
    price: 1100,
    desc: "Quantum Dot 4K QLED TV with Dolby Atmos and 120Hz refresh rate.",
    availability: true,
  },
  {
    product: "Pioneer Android TV",
    price: 650,
    desc: "Android TV with Google Play Store and built-in voice search.",
    availability: true,
  },
  {
    product: "JVC 8K HDR Smart TV",
    price: 1150,
    desc: "8K HDR Smart TV with IMAX Enhanced and Dolby Atmos.",
    availability: true,
  },
  {
    product: "Magnavox LED TV",
    price: 700,
    desc: "LED TV with Wide Color Enhancer and Clean Cable Solution.",
    availability: true,
  },
  {
    product: "Polaroid Premium OLED TV",
    price: 1200,
    desc: "Premium OLED TV with AI Sound Pro and Filmmaker Mode.",
    availability: true,
  },
  {
    product: "Roku Android Smart TV",
    price: 750,
    desc: "Android Smart TV with voice remote and built-in Chromecast.",
    availability: false,
  },
];
