export const Data = [
  {
    img: "https://images.pexels.com/photos/14745352/pexels-photo-14745352.png?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Apple",
    price: 1.99,
    quantity: 50,
    description: "Fresh red apple",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/7194915/pexels-photo-7194915.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Banana",
    price: 0.79,
    quantity: 70,
    description: "Ripe yellow banana",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/2592576/pexels-photo-2592576.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Orange",
    price: 1.49,
    quantity: 40,
    description: "Juicy orange fruit",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/2280550/pexels-photo-2280550.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Carrot",
    price: 0.89,
    quantity: 60,
    description: "Fresh orange carrot",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/5644929/pexels-photo-5644929.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Broccoli",
    price: 1.29,
    quantity: 30,
    description: "Green broccoli florets",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/6107772/pexels-photo-6107772.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Chicken Breast",
    price: 5.99,
    quantity: 20,
    description: "Skinless, boneless chicken breast",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/3296279/pexels-photo-3296279.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Salmon",
    price: 8.99,
    quantity: 15,
    description: "Fresh salmon fillet",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/4110260/pexels-photo-4110260.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Rice",
    price: 2.49,
    quantity: 25,
    description: "Long-grain white rice",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/3789535/pexels-photo-3789535.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Eggs",
    price: 2.79,
    quantity: 40,
    description: "Farm-fresh large eggs",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/7282733/pexels-photo-7282733.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Milk",
    price: 3.49,
    quantity: 30,
    description: "Fresh cow's milk",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/7693950/pexels-photo-7693950.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Bread",
    price: 2.99,
    quantity: 40,
    description: "Whole wheat bread loaf",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/3186254/pexels-photo-3186254.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Cheese",
    price: 4.79,
    quantity: 25,
    description: "Cheddar cheese block",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/39579/tomato-red-fruit-vegetables-39579.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Tomato",
    price: 0.99,
    quantity: 35,
    description: "Ripe red tomato",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/4110460/pexels-photo-4110460.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Potato",
    price: 1.29,
    quantity: 45,
    description: "Fresh potato",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/1194434/pexels-photo-1194434.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Onion",
    price: 0.69,
    quantity: 55,
    description: "Yellow onion",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/3016319/pexels-photo-3016319.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Lettuce",
    price: 1.19,
    quantity: 40,
    description: "Fresh green lettuce",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/3297808/pexels-photo-3297808.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Cucumber",
    price: 1.29,
    quantity: 35,
    description: "Crisp cucumber",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/4144459/pexels-photo-4144459.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Avocado",
    price: 1.99,
    quantity: 20,
    description: "Ripe avocado",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/2264241/pexels-photo-2264241.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Grapes",
    price: 3.49,
    quantity: 30,
    description: "Sweet red grapes",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/2459870/pexels-photo-2459870.png?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Strawberries",
    price: 2.99,
    quantity: 25,
    description: "Juicy red strawberries",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/1395958/pexels-photo-1395958.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Blueberries",
    price: 4.99,
    quantity: 20,
    description: "Fresh blueberries",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/7194784/pexels-photo-7194784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Pineapple",
    price: 2.99,
    quantity: 25,
    description: "Sweet pineapple slices",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/9223283/pexels-photo-9223283.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Watermelon",
    price: 3.49,
    quantity: 15,
    description: "Juicy watermelon chunks",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/5792329/pexels-photo-5792329.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    foodname: "Pizza",
    price: 7.99,
    quantity: 10,
    description: "Pepperoni pizza",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/1108117/pexels-photo-1108117.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Hamburger",
    price: 6.49,
    quantity: 12,
    description: "Beef hamburger",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/2446908/pexels-photo-2446908.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "French Fries",
    price: 3.99,
    quantity: 18,
    description: "Crispy french fries",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/5820040/pexels-photo-5820040.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Ice Cream",
    price: 5.49,
    quantity: 8,
    description: "Vanilla ice cream",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/12395279/pexels-photo-12395279.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Chocolate",
    price: 2.99,
    quantity: 22,
    description: "Milk chocolate bar",
    status: "React",
  },
  {
    img: "https://images.pexels.com/photos/10902846/pexels-photo-10902846.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Coca-Cola",
    price: 1.29,
    quantity: 30,
    description: "Carbonated soft drink",
    status: "Pending",
  },
  {
    img: "https://images.pexels.com/photos/4144459/pexels-photo-4144459.jpeg?auto=compress&cs=tinysrgb&w=1600",
    foodname: "Avocado",
    price: 1.99,
    quantity: 20,
    description: "Ripe avocado",
    status: "React",
  },
];
